[build]
  command = "npm run build"
  publish = "out"           # ← use "out" if you do `next export`
                            # ← use ".next" if you deploy serverless (default)

# Optional but nice – makes netlify dev even faster
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"